spring.application.name=core-banking

spring.datasource.url=jdbc:oracle:thin:@10.10.10.194:1522:training
spring.datasource.username=angular1
spring.datasource.password=orcl123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Multipart file
# Enable Multipart Uploads
spring.servlet.multipart.enabled=true

# Maximum file size for a single upload
spring.servlet.multipart.max-file-size=20MB

# Maximum total request size
spring.servlet.multipart.max-request-size=25MB